# Recipe for flet-libcrc32c package
# Google CRC32C library built from source for mobile platforms
package:
  name: flet-libcrc32c
  version: "1.1.2"

source: url
url: https://github.com/google/crc32c/archive/refs/tags/1.1.2.tar.gz

host_dependencies:
  - cmake
