# Recipe for flet-libcpp-shared package
# This package extracts libc++_shared.so from the Android NDK
package:
  name: flet-libcpp-shared
  version: "27.2.12479018"

# Use a placeholder source - actual binary comes from NDK
source: url
url: https://github.com/flet-dev/awesome-flet/archive/refs/heads/main.zip

# Note: This package is Android-specific and extracts the shared library from NDK
# For proper implementation, would need a custom build script
