# Recipe for pillow package
package:
  name: pillow

# Pillow requires zlib for PNG support
host_dependencies:
  - zlib1g-dev

# Override cibuildwheel config to skip before_all script that doesn't exist in PyPI package
cibw_before_all: ""  # Disable before_all script
cibw_config_settings: ""  # Disable config settings that expect vendored libraries
