# Recipe for pillow package
package:
  name: pillow

# Pillow requires zlib for PNG support, libjpeg for JPEG support, and libtiff for TIFF support
host_dependencies:
  - zlib1g-dev

# Build zlib, libjpeg, and libtiff for the target architecture before building pillow
# These scripts download, cross-compile, and install the libraries for Android/iOS
cibw_before_all: |
  bash $GITHUB_WORKSPACE/recipes/pillow/build_zlib.sh
  bash $GITHUB_WORKSPACE/recipes/pillow/build_libjpeg.sh
  bash $GITHUB_WORKSPACE/recipes/pillow/build_libtiff.sh

# Override cibuildwheel config settings
cibw_config_settings: ""  # Disable config settings that expect vendored libraries

# Environment variables for cross-compilation
cibw_environment:
  # Disable pkg-config to avoid finding host libraries
  PKG_CONFIG: ""

# Patch to auto-detect cross-compiled libraries (zlib, libjpeg, libtiff)
patches:
  - patches/cross_compile_libs_detect.patch

