# Recipe for pycryptodome package
package:
  name: pycryptodome

# Environment variables for cross-compilation
cibw_environment:
  # Disable assembly optimizations that may not work on all architectures
  # This helps avoid build failures on ARM architectures
  CFLAGS: "-DUSE_PORTABLE_MEMCMP"
