package:
  name: numpy

host_dependencies:
  - libopenblas-dev
  - liblapack-dev

# Disable features that require runtime checks during cross-compilation
cibw_environment:
  NPY_DISABLE_BACKTRACE: "1"
  NPY_USE_BLAS: "None"
  NPY_USE_LAPACK: "None"
  # Suppress warnings that cause build failures on Android
  CFLAGS: "-Wno-unknown-attributes -Wno-unused-value -Wno-ignored-attributes"
  CXXFLAGS: "-Wno-unknown-attributes -Wno-unused-value -Wno-ignored-attributes"

# Create placeholder script that numpy's build expects and configure cross-compilation
cibw_before_all: |
  # Create the missing cibw_before_build.sh script if numpy expects it
  if [ ! -f "./tools/wheels/cibw_before_build.sh" ]; then
    mkdir -p ./tools/wheels
    cat > ./tools/wheels/cibw_before_build.sh << 'SCRIPT_EOF'
  #!/bin/bash
  # Placeholder script for numpy build on Android/iOS
  set -e
  echo "NumPy cibw_before_build.sh placeholder for cross-compilation"
  SCRIPT_EOF
    chmod +x ./tools/wheels/cibw_before_build.sh
  fi
  
  # Create comprehensive Meson cross file for cross-compilation
  cat > /tmp/meson_cross_file.txt << 'MESON_EOF'
  [properties]
  needs_exe_wrapper = true
  skip_sanity_check = true
  
  [built-in options]
  c_args = ['-Wno-unknown-attributes', '-Wno-unused-value', '-Wno-ignored-attributes']
  cpp_args = ['-Wno-unknown-attributes', '-Wno-unused-value', '-Wno-ignored-attributes']
  
  [host_machine]
  system = 'android'
  cpu_family = 'aarch64'
  cpu = 'armv8'
  endian = 'little'
  MESON_EOF

# Configure meson-python to use the cross file
cibw_config_settings: "setup-args=--cross-file=/tmp/meson_cross_file.txt"

