package:
  name: numpy
  # version: ""  # Optional: leave empty to use latest

# Pip dependencies needed for building numpy
# Cython is required for building numpy's extension modules
# meson-python is the build backend (numpy uses meson build system)
pip_dependencies:
  - Cython
  - meson-python

# Environment variables for the build
# PKG_CONFIG="" prevents finding host system libraries during cross-compilation
cibw_environment:
  PKG_CONFIG: ""

# Build script to set up cross-compilation
# For mobile platforms, we need to configure meson properly without patches
cibw_before_all: |
  # Create a simple cross-compilation setup script
  if [ "$CIBW_PLATFORM" = "android" ] || [ "$CIBW_PLATFORM" = "ios" ]; then
    echo "Setting up mobile platform build for $CIBW_PLATFORM..."
  fi

# CIBW config settings to pass to meson-python
# These settings configure numpy build for mobile platforms:
# - allow-noblas=true: Build without BLAS/LAPACK for simpler mobile builds
# - disable-svml=true: Disable Intel SVML for ARM portability
cibw_config_settings: setup-args=-Dallow-noblas=true setup-args=-Ddisable-svml=true
