# Recipe for flet-libxslt package
# libxslt library built from source for mobile platforms
package:
  name: flet-libxslt
  version: "1.1.32"

source: url
url: http://xmlsoft.org/download/libxslt-1.1.32.tar.gz

host_dependencies:
  - zlib1g-dev

# Depends on flet-libxml2
# requirements:
#   host:
#     - flet-libxml2

# Apply mobile-specific patches
patches:
  - patches/mobile.patch
