# Recipe for flet-libjpeg package  
# libjpeg-turbo library built from source for mobile platforms
package:
  name: flet-libjpeg
  version: "3.0.90"

source: url
url: https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/3.0.90/libjpeg-turbo-3.0.90.tar.gz

host_dependencies:
  - cmake
  - nasm
