# Recipe for cryptography package
package:
  name: cryptography

# Skip for mobile platforms due to Rust/maturin cross-compilation complexity
# Maturin requires matching host/target Python interpreters and proper Rust toolchains
# which is not feasible in the current cibuildwheel Android/iOS setup
skip_platforms:
  - android
  - ios

host_dependencies:
  - libssl-dev
  - libffi-dev
  - cargo
  - rustc
