# Recipe for cryptography package
package:
  name: cryptography

# Skip iOS due to Rust/maturin cross-compilation complexity with Xcode toolchain
# Android builds are now supported with PYO3_CROSS=1 environment variable
skip_platforms:
  - ios

host_dependencies:
  - libssl-dev
  - libffi-dev
  - cargo
  - rustc
