# Recipe for flet-libpng package
# libpng library built from source for mobile platforms
package:
  name: flet-libpng
  version: "1.6.43"

source: url
url: https://github.com/pnggroup/libpng/archive/refs/tags/v1.6.43.tar.gz

host_dependencies:
  - zlib1g-dev

# Apply mobile-specific patches
patches:
  - patches/config.patch
